---
language: ruby
bundler_args: --without system_tests
script: "bundle exec metadata-json-lint --strict-license --fail-on-warnings metadata.json && bundle exec rake spec SPEC_OPTS='--format documentation'"

sudo: false

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.1"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
    - PUPPET_GEM_VERSION="~> 3.8.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4.0"
notifications:
  email: false
